import streamlit as st
import pandas as pd
import plotly.graph_objects as go
import folium
from streamlit_folium import st_folium
from src.inference import predict_soc
from geopy.geocoders import Nominatim
from src.validator import get_validation_soc
from fpdf import FPDF
import io

# 1. Page Setup
st.set_page_config(
    page_title="BioGeo-SOC Advanced", 
    page_icon="🌱", 
    layout="wide"
)

# Persistent Data Storage
if 'results' not in st.session_state:
    st.session_state.results = None

# Sidebar
with st.sidebar:
    st.header("⚙️ System Specs")
    st.success("✅ Model: Random Forest")
    st.info("🛰️ Sensor: Sentinel-2")
    st.markdown("---")
    st.caption("BioGeo-SOC v1.0")
    st.caption("Gujarat Soil Analysis")

st.title("🌱 Soil Organic Carbon (SOC) Advanced Analytics")
st.markdown("*Predict soil health using satellite data for any location in Gujarat*")

# Search UI
geolocator = Nominatim(user_agent="soc_predictor_amnex", timeout=10)

col1, col2 = st.columns([3, 1])
with col1:
    location_name = st.text_input(
        "Enter Village/Location Name", 
        placeholder="e.g., Chotila, Dholka, Bavla"
    )
with col2:
    st.markdown("<br>", unsafe_allow_html=True)
    analyze_btn = st.button("🔍 Analyze Location", type="primary", use_container_width=True)

if analyze_btn:
    if location_name:
        with st.spinner("🛰️ Fetching Satellite Data & Processing..."):
            try:
                location = geolocator.geocode(f"{location_name}, Gujarat, India")
                
                if location:
                    st.info(f"📍 Found: {location.address}")
                    
                    # Get prediction
                    soc_val, soc_std, indices = predict_soc(
                        location.latitude, 
                        location.longitude,
                        use_grid_average=True,
                        grid_size=3
                    )
                    
                    # Fetch validation value
                    ground_truth = get_validation_soc(location.latitude, location.longitude)
                    
                    if soc_val is not None:
                        st.session_state.results = {
                            'soc': soc_val, 
                            'std': soc_std, 
                            'indices': indices,
                            'lat': location.latitude, 
                            'lon': location.longitude, 
                            'addr': location.address,
                            'ground_truth': ground_truth
                        }
                        st.success("✅ Analysis Complete!")
                    else:
                        st.error("❌ No satellite data available for this location.")
                else:
                    st.error("❌ Location not found.")
                    
            except Exception as e:
                st.error(f"❌ Error: {str(e)}")
    else:
        st.warning("⚠️ Please enter a location name")

# PDF Generation Function
def generate_pdf(res):
    """Generate PDF report from analysis results"""
    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="BioGeo-SOC Soil Analysis Report", ln=True, align='C')
    pdf.ln(10)
    
    # Location Info
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"Location: {res['addr']}", ln=True)
    pdf.cell(200, 10, txt=f"Coordinates: {res['lat']:.4f}, {res['lon']:.4f}", ln=True)
    pdf.ln(5)
    
    # Results Table
    pdf.set_fill_color(200, 220, 255)
    pdf.cell(90, 10, "Metric", border=1, fill=True)
    pdf.cell(90, 10, "Value", border=1, fill=True, ln=True)
    
    pdf.cell(90, 10, "AI Predicted SOC", border=1)
    pdf.cell(90, 10, f"{res['soc']:.2f} g/kg", border=1, ln=True)
    
    if res.get('ground_truth'):
        pdf.cell(90, 10, "SoilGrids (Truth)", border=1)
        pdf.cell(90, 10, f"{res['ground_truth']:.2f} g/kg", border=1, ln=True)
        
    pdf.cell(90, 10, "NDVI (Vegetation)", border=1)
    pdf.cell(90, 10, f"{res['indices']['ndvi']:.3f}", border=1, ln=True)
    
    pdf.cell(90, 10, "EVI (Enhanced Veg)", border=1)
    pdf.cell(90, 10, f"{res['indices']['evi']:.3f}", border=1, ln=True)
    
    pdf.cell(90, 10, "NDWI (Water Index)", border=1)
    pdf.cell(90, 10, f"{res['indices']['ndwi']:.3f}", border=1, ln=True)
    
    # Footer
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(0, 10, "Generated by BioGeo-SOC Advanced Analytics System", align='C')
    
    return pdf.output(dest='S').encode('latin-1')

# --- DASHBOARD LAYOUT ---
if st.session_state.results:
    res = st.session_state.results
    
    st.markdown("---")
    st.markdown(f"### 📊 Analysis for: {res['addr']}")
    
    # ROW 1: LARGE METRICS (Updated to include Truth and Accuracy)
    m1, m2, m3, m4, m5 = st.columns(5)
    
    m1.metric("Predicted SOC", f"{res['soc']:.2f} g/kg")
    
    # Display Validation Truth from GeoTIFF
    if res.get('ground_truth') is not None:
        m2.metric("SoilGrids (Truth)", f"{res['ground_truth']:.2f} g/kg")
        # Accuracy Calculation
        error = abs(res['soc'] - res['ground_truth'])
        accuracy = max(0, 100 - (error / res['ground_truth'] * 100)) if res['ground_truth'] > 0 else 0
        m3.metric("Model Accuracy", f"{accuracy:.1f}%")
    else:
        m2.metric("SoilGrids (Truth)", "N/A")
        m3.metric("Model Accuracy", "N/A")

    m4.metric("NDVI (Veg)", f"{res['indices']['ndvi']:.3f}")
    
    # Confidence logic
    if res['std'] < 1.0:
        confidence = "High ✅"
    elif res['std'] < 2.0:
        confidence = "Medium ⚠️"
    else:
        confidence = "Low ❌"
    
    m5.metric("Confidence", confidence)

    # ROW 2: SIDE-BY-SIDE CHARTS
    st.markdown("---")
    chart_col1, chart_col2 = st.columns(2)
    
    with chart_col1:
        st.subheader("🌡️ Soil Quality Gauge")
        fig_gauge = go.Figure(go.Indicator(
            mode="gauge+number+delta",
            value=res['soc'],
            title={'text': "SOC (g/kg)"},
            delta={'reference': 15},
            gauge={
                'axis': {'range': [0, 25]},
                'bar': {'color': "darkblue"},
                'steps': [
                    {'range': [0, 10], 'color': "#ff4b4b"},
                    {'range': [10, 20], 'color': "#ffa500"},
                    {'range': [20, 25], 'color': "#2ecc71"}
                ],
                'threshold': {
                    'line': {'color': "red", 'width': 4},
                    'thickness': 0.75,
                    'value': 15
                }
            }
        ))
        fig_gauge.update_layout(margin=dict(l=20, r=20, t=50, b=20), height=350)
        st.plotly_chart(fig_gauge, use_container_width=True, key="g_final")

    with chart_col2:
        st.subheader("🕸️ Environmental Signature")
        fig_radar = go.Figure(go.Scatterpolar(
            r=[abs(res['indices']['ndvi']), abs(res['indices']['evi'])/3, abs(res['indices']['ndwi'])],
            theta=['NDVI', 'EVI', 'NDWI'],
            fill='toself',
            fillcolor='rgba(46, 139, 87, 0.4)',
            line=dict(color='seagreen')
        ))
        fig_radar.update_layout(
            polar=dict(radialaxis=dict(visible=True, range=[0, 1])),
            showlegend=False, height=350, margin=dict(l=40, r=40, t=40, b=40)
        )
        st.plotly_chart(fig_radar, use_container_width=True, key="r_final")

    # ROW 3: FULL WIDTH MAP
    st.markdown("---")
    st.subheader("🗺️ Satellite Context & Location")
    
    m = folium.Map(
        location=[res['lat'], res['lon']], 
        zoom_start=15,
        tiles='https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}',
        attr='Google Satellite'
    )
    folium.Marker(
        [res['lat'], res['lon']],
        popup=f"SOC: {res['soc']:.2f} g/kg",
        icon=folium.Icon(color='green', icon='leaf', prefix='fa')
    ).add_to(m)
    
    st_folium(m, width=None, height=450, key="map_final")
    
    # Interpretation
    st.markdown("---")
    st.subheader("📋 Interpretation")
    col_int1, col_int2 = st.columns(2)
    with col_int1:
        st.markdown("**Soil Quality:**")
        if res['soc'] < 10: 
            st.warning("🟡 Low soil carbon")
        elif res['soc'] < 20: 
            st.success("🟢 Good soil carbon")
        else: 
            st.info("🔵 High soil carbon")
    with col_int2:
        st.markdown("**Vegetation Health:**")
        if res['indices']['ndvi'] < 0.2: 
            st.warning("🟡 Sparse vegetation")
        elif res['indices']['ndvi'] < 0.6: 
            st.success("🟢 Moderate vegetation")
        else: 
            st.info("🔵 Dense vegetation")
    
    # PDF Download Button
    st.markdown("---")
    st.subheader("📄 Export Report")
    
    try:
        pdf_data = generate_pdf(res)
        st.download_button(
            label="📥 Download PDF Report",
            data=pdf_data,
            file_name=f"SOC_Report_{location_name.replace(' ', '_')}.pdf",
            mime="application/pdf",
            use_container_width=True
        )
    except Exception as e:
        st.error(f"Error generating PDF: {str(e)}")
        
else:
    st.info("👆 Enter a location name above to start analysis")